# Build settings
theme: minima
plugins:
  - jekyll-feed

# Dependencies
markdown:         kramdown
pygments:         true
highlighter:      rouge

# Permalinks
permalink:        pretty

baseurl: '/wrench-pedagogic-modules'

# Setup
title:            'WRENCH PEDAGOGIC MODULES'
tagline:          'Distributed Computing Courseware'
description:      'WRENCH Pedagogic Modules.'

author:
  name:           'WRENCH Team'
  url:            https://wrench-project.org

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/lanyon

# include directory for pages
# include: ['_pages']

collections:
  pedagogic_modules:
      output: true
      permalink: /pedagogic_modules/:path/
